"""update event schema for new fields

Revision ID: update_event_schema_for_new_fields
Revises: e4049089f6a3
Create Date: 2025-01-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'update_event_schema_for_new_fields'
down_revision = 'e4049089f6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename title column to name
    op.alter_column('events', 'title', new_column_name='name')
    
    # Remove description column
    op.drop_column('events', 'description')
    
    # Add max_capacity column
    op.add_column('events', sa.Column('max_capacity', sa.Integer(), nullable=True))
    
    # Update index name from title to name
    op.drop_index('ix_events_title', table_name='events')
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename name column back to title
    op.alter_column('events', 'name', new_column_name='title')
    
    # Add description column back
    op.add_column('events', sa.Column('description', sa.String(), nullable=True))
    
    # Remove max_capacity column
    op.drop_column('events', 'max_capacity')
    
    # Update index name from name back to title
    op.drop_index('ix_events_name', table_name='events')
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    # ### end Alembic commands ### 